---
env:
  node: true

extends:
  - 'airbnb-base'
  - 'eslint:recommended'

parserOptions:
  ecmaVersion: latest

rules:
  quotes: [error, single]
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
